import React, { Component } from 'react';
import Layout from '../../components/Layout';
import SupplyEtherForm from '../../components/SupplyEtherForm';
import { Card, Grid, Button} from 'semantic-ui-react';
import { Link } from '../../routes';
import HouseholdContract from '../../ethereum/household';
import web3 from '../../ethereum/web3';
import SetExchange from '../../components/SetExchange';

class HouseholdPage extends Component {
    static async getInitialProps(props) {
        const household = HouseholdContract(props.query.address);
        const summary = await household.methods.getSmartMeterDetails().call();
        const balance = await web3.eth.getBalance(props.query.address);
        const exchangeAddress = await household.methods.exchangeAddress().call();
        
        return { 
            owner: summary[0],
            address: props.query.address,
            demand: summary[1],
            supply: summary[2],
            batteryCapacity: summary[3],
            amountOfCharge: summary[4],
            excessEnergy: summary[5],
            balance: balance,
            exchangeAddress: exchangeAddress
         }
    }

    renderCards(){
        const {
            owner,
            demand,
            supply,
            batteryCapacity,
            amountOfCharge,
            excessEnergy,
            balance,
            exchangeAddress
          } = this.props;
      
          const items = [
            {
              header: owner,
              meta: 'Address of Owner',
              description:
                'The owner created this contract and can submit Bids and Asks to the exchange',
              style: { overflowWrap: 'break-word' }
            },
            {
              header: this.props.address,
              meta: 'Address of the Household Contract',
              description:
                'This address serves as an identification of the household contract. It can be used to send ether to if someone desires to buy electricity from it.',
              style: { overflowWrap: 'break-word' }
            },
            {
              header: demand,
              meta: 'Current Demand of Household',
              description:
                'Current demand indicates the load of the household in kWh'
            },
            {
              header: supply,
              meta: 'Current Supply of Household',
              description:
                'Current supply indicates the generation of the household in kWh'
            },
            {
                header: batteryCapacity,
                meta: 'Battery Capacity of the Household',
                description:
                  'The full battery capacity of the household in kWh.'
            },
            {
                header: amountOfCharge,
                meta: 'Current Amount of Charge of the Battery',
                description:
                  'Current amount of charge of the battery of the household in kWh.'
            },
            {
                header: excessEnergy,
                meta: 'Current Excess of Energy of the Household',
                description:
                  'Current excess of energy being generated by the household in kWh.'
            },
            {
              header: web3.utils.fromWei(balance, 'ether'),
              meta: 'Household Contract Balance (ether)',
              description:
                'The balance is how much ether a household contract holds.'
            },
            {
                header: exchangeAddress,
                meta: 'Exchange Address',
                description:
                  'The address of the exchange in which this contract is connected to.',
                  style: { overflowWrap: 'break-word' }
              }
            ];
            return <Card.Group items={items} />;
    }

    render() {
        return (
            <Layout>
                <h1>Household Page Summary</h1>
                <Link route={'exchange'} params={{ address : this.props.address}}>
                <Button position='right' secondary>Go to Exchange</Button>
                </Link>
                <Grid style={{ marginTop: '10px', marginBottom: '10px' }}>
                    <Grid.Row>
                    <Grid.Column width={10}>{this.renderCards()}</Grid.Column>
                    <Grid.Column width={6}>
                    <SupplyEtherForm address={this.props.address} style={{padding:'10', marginBottom: '100px'}}/>
                    <p></p>
                    <p></p>
                    <SetExchange address={this.props.address} style={{marginTop: '10px'}}/>
                    </Grid.Column>
                    </Grid.Row>
                </Grid>
                
            </Layout>
        );
    }
}

export default HouseholdPage;
